### ISSUE TITLE
Next gen .NET SDK metadata update for multiselect

### ISSUE THREAD

**Issue by ma-gis** [box/box-dotnet-sdk-gen#345]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

Here is my code snippet to update doctypes which I am passing as array

```await boxService._client.FolderMetadata.UpdateFolderMetadataByIdAsync(folderId: "123", scope: UpdateFolderMetadataByIdScope.Enterprise, 
        templateKey: "arms", requestBody: Array.AsReadOnly(new[] { new UpdateFolderMetadataByIdRequestBody() { Op = UpdateFolderMetadataByIdRequestBodyOpField.Replace, Path = "/doctypes", Value = "[\"Asbuilt\", \"RW Plat\"]" } }));
```
I had contacted Box Platform Support Team and they responded that client (Box .NET SDK) should not have \ prefixed.

So I am suspecting some bug where this information is passed to API endpoint in .NET SDK code.

Thanks for the additional information. I can confirm that, on our end, the request body which is being evaluated in the api call is
[{"op":"replace","path":"\/doctypes","value":"[\"Asbuilt\",\"RW Plat\"]"}]
 
In my own testing in Postman PUT request on a multiselect metadata instance without backspaces received a successful 200 response: 
 
curl --location --request PUT 'https://api.box.com/2.0/files/1715987212712/metadata/enterprise/multiselect' \
--header 'Content-Type: application/json-patch+json' \
--header 'Authorization: ••••••' \
--data '[
{
"op": "add",
"path": "/dwarfs",
"value":["doc"]
}
]'
 
Whereas when backslashes were introduced to the value like so:
curl --location --request PUT 'https://api.box.com/2.0/files/1715987212712/metadata/enterprise/multiselect' \
--header 'Content-Type: application/json-patch+json' \
--header 'Authorization: ••••••' \
--data '[
{
"op": "add",
"path": "/dwarfs",
"value":[\"doc"]
}
]'
 
A 400 invalid parameter error is received. You may likewise isolate the issue to the particular C# code in question by taking similar steps. 

### Steps to Reproduce

1. Create a template 'arms' with multiselect field type let's say doctypes with acceptable values as doc1,doct2 and doc3
2. Run following code 

```
UpdateFolderMetadataByIdScope.Enterprise, templateKey: "arms", requestBody: Array.AsReadOnly(new[] { new UpdateFolderMetadataByIdRequestBody() { Op = UpdateFolderMetadataByIdRequestBodyOpField.Replace, Path = "/doctypes", Value = "[\"doc1\", \"doc2\"]" } }));
```
 

### Expected Behavior

SDK should handle serialization of array items and remove backward slash before making call to API endpoint. 

### Error Message, Including Stack Trace

System.AggregateException: One or more errors occurred. ({"message":"Encountered invalid value for template field key=doctypes with id=3de83589-70dc-414a-92e1-7aa48d1e77be","code":"bad_request","request_id":"j8bccbhw8f93hatm"})
---> Box.Sdk.Gen.BoxApiException: {"message":"Encountered invalid value for template field key=doctypes with id=3de83589-70dc-414a-92e1-7aa48d1e77be","code":"bad_request","request_id":"j8bccbhw8f93hatm"}
   at Box.Sdk.Gen.Internal.HttpClientAdapter.FetchAsync(FetchOptions options)
   at Box.Sdk.Gen.Managers.FolderMetadataManager.UpdateFolderMetadataByIdAsync(String folderId, UpdateFolderMetadataByIdScope scope, String templateKey, IReadOnlyList`1 requestBody, UpdateFolderMetadataByIdHeaders headers, Nullable`1 cancellationToken)
   at UpdateEFL.Program.ExecuteMainAsync(AppConfig appConfig) in C:\gisu-repos\UpdateEFL2016\UpdateEFL\Program.cs:line 163
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()

### Versions Used

.NET SDK: 1.5.0
.NET: 8.0

[sdk-docs]: https://github.com/box/box-dotnet-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-dotnet-sdk-gen/search?type=Issues

**Comment by mwwoda** [comment]
It looks like issue lies within specification. In case of multiselect, array of values should be send. Spec describes this field as string https://developer.box.com/reference/put-folders-id-metadata-id-id/#param-%253Citem%253E-value which is incorrect. Due to the fact that we generate models based on spec, it's affecting this operation. I raised an issue internally.

In the meantime, you could try to send custom request as a workaround - https://github.com/box/box-dotnet-sdk-gen/blob/main/docs/Client.md#make-custom-http-request

**Comment by ma-gis** [comment]
Thanks for sharing workaround link and it worked.

**Comment by mwwoda** [comment]
Hello,

Schema for updating metadata was fixed. This PR that was generated on SDK side https://github.com/box/box-dotnet-sdk-gen/pull/474/files#diff-48dbd439ead2354644bf00b6d96d6ab8580bdfc3a56d4cbba84a31cb4c81abb7. We also have a test showing how to update metadata - https://github.com/box/box-dotnet-sdk-gen/blob/main/Box.Sdk.Gen.Tests.Integration/Test/FolderMetadata/FolderMetadataManagerTests.cs#L24. We still need to release a package with change that makes passing collections easier (PR here - https://github.com/box/box-dotnet-sdk-gen/pull/483). But it should be already possible to update the metadata for folder due to the spec change.

I'm closing this issue for now. In case of any problems, feel free to reopen this issue.
